### ISSUE TITLE
UI Beautification required

### ISSUE THREAD

**Issue by agamswaroop619** [agamswaroop619/timeout#1]
TimeOut requires few changes to be perfect for use! Users need to find it attractive. 
Use the below docs for reference:
- https://www.w3schools.com/css/
- https://getbootstrap.com/docs/5.3/getting-started/introduction/

- [x] Add colour/ extra styles
- [x] Make the border rounded

**Comment by harshitprg** [comment]
### **fix: UI changes**

1. Fixed the UI design with CSS and Bootstrap Frameworks
2. The updated UI provides a more intuitive and user-friendly experience.
3. Responsive UI
![Screenshot 2023-11-21 195031](https://github.com/agamswaroop619/timeout/assets/112307359/113d25f3-364c-4cba-ac1f-055681dc1cb0)

**Comment by agamswaroop619** [comment]
@harshitprg 
Thank you for your efforts.
Please add a PR of your fork so that we can update from here.

**Comment by harshitprg** [comment]
Sure!
